<?php
require_once __DIR__ . '/src/weather.php';
$rawCities = isset($_GET['cities']) ? (string) $_GET['cities'] : 'Berlin';
$cityNames = array_values(array_filter(array_map('trim', explode(',', $rawCities))));
$cityNames = array_slice(array_unique($cityNames), 0, 3);
$cities = fetchCities($cityNames ?: ['Berlin']);
$valid = array_values(array_filter($cities, fn($city) => !isset($city['error'])));
$winner = function (string $metric, bool $lowest = false) use ($valid): array {
    if (!$valid) return [];
    $values = [];
    foreach ($valid as $index => $city) $values[$index] = (float) ($city[$metric] ?? 0);
    $best = $lowest ? min($values) : max($values);
    return array_keys(array_filter($values, fn($value) => $value === $best));
};
$warmest = $winner('temp'); $sunniest = $winner('clouds', true); $driest = $winner('precipitation', true);
function h(string $value): string { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>CityLens Weather</title><link rel="icon" href="favicon.ico"><script src="skycons/skycons.js"></script><style>
:root{--accent:#667eea;--bg:#f1f5f9;--card:#fff;--text:#263244;--muted:#64748b}*{box-sizing:border-box}body{margin:0;padding:24px;background:linear-gradient(135deg,var(--bg),#dbeafe);color:var(--text);font:16px Inter,system-ui,sans-serif}.container{max-width:1200px;margin:auto}.app-header{text-align:center;margin:28px 0}.app-header h1{margin:0 0 8px;font-size:2.4rem}.subtitle{color:var(--muted)}.search{text-align:center;margin-bottom:24px}.search input{width:min(700px,90%);padding:13px 16px;border:1px solid #cbd5e1;border-radius:12px;font-size:1rem}.search button{padding:13px 20px;margin-left:6px;border:0;border-radius:12px;background:var(--accent);color:white;font-weight:600}.comparison{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}.weather-card{background:var(--card);border-radius:20px;padding:24px;box-shadow:0 12px 30px #0001}.weather-icon-container{text-align:center}.weather-icon{width:96px;height:96px}.weather-info p{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #e2e8f0;padding:9px 0;margin:0}.weather-label{color:var(--muted);font-size:.85rem;text-transform:uppercase}.weather-value{font-weight:600;text-align:right}.winner{color:var(--accent);font-size:.75rem;margin-left:5px}.forecast{margin-top:18px}.forecast h3{font-size:1rem}.forecast-row{display:grid;grid-template-columns:70px 1fr auto;gap:8px;padding:7px 0;border-top:1px solid #e2e8f0;font-size:.88rem}.error-card{border:2px solid #f87171}.footer{text-align:center;color:var(--muted);margin:28px}@media(max-width:600px){body{padding:14px}.app-header h1{font-size:2rem}.search button{margin-top:8px}}
</style></head><body><div class="container"><header class="app-header"><h1>CityLens Weather</h1><p class="subtitle">Compare weather in up to three cities</p></header><form class="search"><input name="cities" value="<?= h(implode(', ', $cityNames)) ?>" placeholder="Berlin, Lisbon, Tokyo" aria-label="Cities"><button>Compare</button></form><main class="comparison">
<?php foreach ($cities as $index => $city): ?><article class="weather-card <?= isset($city['error']) ? 'error-card' : '' ?>"><?php if (isset($city['error'])): ?><h2><?= h($city['requested']) ?></h2><p><?= h($city['error']) ?></p><?php continue; endif; ?><div class="weather-icon-container"><canvas class="weather-icon" id="weather-icon-<?= $index ?>" width="96" height="96"></canvas></div><h2><?= h($city['name']) ?>, <?= h($city['country']) ?></h2><div class="weather-info"><p><span class="weather-label">Condition</span><span class="weather-value"><?= h(ucfirst($city['condition'])) ?></span></p><p><span class="weather-label">Temperature</span><span class="weather-value"><?= $city['temp'] ?>°C <?php if (in_array($index,$warmest,true)): ?><span class="winner">warmest</span><?php endif; ?></span></p><p><span class="weather-label">Feels like</span><span class="weather-value"><?= $city['feels_like'] ?>°C</span></p><p><span class="weather-label">Humidity</span><span class="weather-value"><?= $city['humidity'] ?>%</span></p><p><span class="weather-label">Clouds</span><span class="weather-value"><?= $city['clouds'] ?>% <?php if (in_array($index,$sunniest,true)): ?><span class="winner">sunniest</span><?php endif; ?></span></p><p><span class="weather-label">Precipitation</span><span class="weather-value"><?= $city['precipitation'] ?>% <?php if (in_array($index,$driest,true)): ?><span class="winner">driest</span><?php endif; ?></span></p><p><span class="weather-label">Wind</span><span class="weather-value"><?= $city['wind'] ?> m/s</span></p></div><div class="forecast"><h3>5-day forecast</h3><?php foreach ($city['forecast'] as $day): ?><div class="forecast-row"><span><?= h(date('D',strtotime($day['date']))) ?></span><span><?= h(ucfirst($day['description'])) ?></span><strong><?= $day['temp'] ?>°C</strong></div><?php endforeach; ?></div></article><?php endforeach; ?></main><div class="footer">Powered by OpenWeatherMap</div></div><script>
const skycons=new Skycons({monochrome:false});<?php foreach ($cities as $index=>$city): if (!isset($city['error'])): ?>skycons.add('weather-icon-<?=$index?>',Skycons[<?= json_encode($city['icon']) ?>]);<?php endif; endforeach; ?>skycons.play();
</script></body></html>
